theme: minima
title: Todds Practice Blog
author: TNT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Practicing making a blog on github pages!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
